services:

  frontend:
    build: ./frontend
    container_name: chatapp_frontend
    depends_on:
      - backend
    networks:
      - master_network
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    env_file:
      - .env

  backend:
    build: ./backend
    container_name: chatapp_backend
    ports:
      - "${PORT:-5000}:5000"
    networks:
      - master_network
    restart: always
    env_file:
      - .env

networks:
  master_network:
    external: true

volumes:
  mongodb_data:  # COMMENT OUT IF USING EXTERNAL MONGODB
  # redis_data:    # COMMENT OUT IF USING EXTERNAL REDIS