services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build: ./frontend
    # ports:
    #  - "80:80"  # Commented out, only nginx exposes port 80
    depends_on:
      - backend
    networks:
      - app-network
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    env_file:
      - .env

  backend:
    build: ./backend
    ports:
      - "${PORT:-5000}:5000"
    networks:
      - app-network
    restart: always
    env_file:
      - .env

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:  # COMMENT OUT IF USING EXTERNAL MONGODB
  # redis_data:    # COMMENT OUT IF USING EXTERNAL REDIS