services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always
    environment:
      - NODE_ENV=production

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_DB_URI=mongodb://mongodb:27017/demo-chat
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=aVerySecureAndRandomSecretKeyForJWTGenerationPleaseChangeMe
      - CORS_ORIGIN=http://YOUR_EC2_PUBLIC_IP
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network
    restart: always

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - app-network
    command: redis-server --requirepass your_redis_password

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: